# -*- coding: utf-8 -*-
"""Detect_cargo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gV1Ht-FB2fHo7xWdE0AhD5RmV4O95iTi
"""

pip install aiogram

import sqlite3

# Подключение к базе (файл создастся автоматически)
conn = sqlite3.connect('cargo.db')
cursor = conn.cursor()

# Создание таблицы
cursor.execute('''
CREATE TABLE IF NOT EXISTS cargos (
    grz TEXT PRIMARY KEY,  -- Номер ГРЗ (уникальный)
    status TEXT,           -- Статус груза
    route TEXT              -- Маршрут (ссылка или описание)
)
''')

conn.commit()
conn.close()

# Добавление записи
def add_cargo(grz, status, route):
    conn = sqlite3.connect('cargo.db')
    cursor = conn.cursor()
    cursor.execute('''
    INSERT INTO cargos (grz, status, route)
    VALUES (?, ?, ?)
    ''', (grz, status, route))
    conn.commit()
    conn.close()

# Пример
add_cargo("A123BC", "В пути", "https://maps.example.com/route1")
add_cargo("B456DE", "Задержан", "https://maps.example.com/route2")

# Получить все грузы
def get_all_cargos():
    conn = sqlite3.connect('cargo.db')
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM cargos")
    result = cursor.fetchall()
    conn.close()
    return result

# Вывести все записи
print("Все грузы:", get_all_cargos())

import sqlite3
from datetime import datetime

# Подключение к базе
conn = sqlite3.connect('cargo.db', check_same_thread=False)
cursor = conn.cursor()

# Проверка существующих колонок
cursor.execute("PRAGMA table_info(cargos)")
columns = [col[1] for col in cursor.fetchall()]

# Миграция таблицы при необходимости
if 'latitude' not in columns:
    cursor.execute("ALTER TABLE cargos ADD COLUMN latitude REAL")
    cursor.execute("ALTER TABLE cargos ADD COLUMN longitude REAL")
    cursor.execute("ALTER TABLE cargos ADD COLUMN last_update TIMESTAMP")
    conn.commit()
    print("Таблица обновлена: добавлены колонки latitude, longitude, last_update")

# Создание таблицы (если не существует)
cursor.execute('''
CREATE TABLE IF NOT EXISTS cargos (
    grz TEXT PRIMARY KEY,
    status TEXT,
    route TEXT,
    latitude REAL,
    longitude REAL,
    last_update TIMESTAMP
)
''')

# Таблица для истории статусов
cursor.execute('''
CREATE TABLE IF NOT EXISTS status_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    grz TEXT,
    status TEXT,
    timestamp TIMESTAMP,
    FOREIGN KEY(grz) REFERENCES cargos(grz)
)
''')

conn.commit()

def add_cargo(grz: str, status: str, route: str, latitude: float, longitude: float):
    """Добавление нового груза"""
    try:
        with conn:
            conn.execute('''
            INSERT INTO cargos (grz, status, route, latitude, longitude, last_update)
            VALUES (?, ?, ?, ?, ?, ?)
            ''', (grz, status, route, latitude, longitude, datetime.now()))

            # Запись в историю статусов
            conn.execute('''
            INSERT INTO status_history (grz, status, timestamp)
            VALUES (?, ?, ?)
            ''', (grz, status, datetime.now()))
    except sqlite3.IntegrityError:
        print(f"Груз с ГРЗ {grz} уже существует")

# Примеры добавления данных
add_cargo(
    grz="A123BC",
    status="В пути",
    route="Москва - Санкт-Петербург",
    latitude=55.7558,
    longitude=37.6173
)

add_cargo(
    grz="B456DE",
    status="Задержан",
    route="Новосибирск - Красноярск",
    latitude=55.0083,
    longitude=82.9357
)

conn.close()

import sqlite3
from datetime import datetime
from typing import Optional

# Подключение к базе с использованием контекстного менеджера
conn = sqlite3.connect('cargo.db', check_same_thread=False)
cursor = conn.cursor()

def initialize_db():
    """Инициализация базы данных и миграции"""

    # Создание основной таблицы с проверкой структуры
    cursor.execute("PRAGMA table_info(cargos)")
    existing_columns = [col[1] for col in cursor.fetchall()]

    required_columns = ['grz', 'status', 'route', 'latitude', 'longitude', 'last_update']

    # Добавляем недостающие колонки
    for column in required_columns:
        if column not in existing_columns:
            if column == 'last_update':
                cursor.execute("ALTER TABLE cargos ADD COLUMN last_update TIMESTAMP")
            else:
                cursor.execute(f"ALTER TABLE cargos ADD COLUMN {column} TEXT")

    # Финальное создание таблицы (на случай если таблица не существовала)
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS cargos (
        grz TEXT PRIMARY KEY,
        status TEXT,
        route TEXT,
        latitude REAL,
        longitude REAL,
        last_update TIMESTAMP
    )
    ''')

    # Создание таблицы истории статусов
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS status_history (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        grz TEXT,
        status TEXT,
        timestamp TIMESTAMP,
        FOREIGN KEY(grz) REFERENCES cargos(grz)
    )
    ''')

    conn.commit()

def add_or_update_cargo(
    grz: str,
    status: str,
    route: str,
    latitude: Optional[float] = None,
    longitude: Optional[float] = None
) -> None:
    """Добавление или обновление информации о грузе"""
    existing_cargo = cursor.execute(
        "SELECT grz FROM cargos WHERE grz = ?", (grz,)
    ).fetchone()

    current_time = datetime.now()

    if existing_cargo:
        # Обновляем существующую запись
        cursor.execute('''
        UPDATE cargos
        SET status = ?, route = ?, latitude = ?, longitude = ?, last_update = ?
        WHERE grz = ?
        ''', (status, route, latitude, longitude, current_time, grz))

        print(f"Груз {grz} обновлен")
    else:
        # Создаем новую запись
        cursor.execute('''
        INSERT INTO cargos
        (grz, status, route, latitude, longitude, last_update)
        VALUES (?, ?, ?, ?, ?, ?)
        ''', (grz, status, route, latitude, longitude, current_time))

        print(f"Груз {grz} добавлен")

    # Записываем историю статуса
    cursor.execute('''
    INSERT INTO status_history (grz, status, timestamp)
    VALUES (?, ?, ?)
    ''', (grz, status, current_time))

    conn.commit()

def get_cargo_info(grz: str) -> dict:
    """Получение информации о грузе"""
    cursor.execute("SELECT * FROM cargos WHERE grz = ?", (grz,))
    result = cursor.fetchone()

    if result:
        return {
            'grz': result[0],
            'status': result[1],
            'route': result[2],
            'latitude': result[3],
            'longitude': result[4],
            'last_update': result[5]
        }
    return None

# Инициализация БД
initialize_db()

# Примеры использования
try:
    # Добавляем/обновляем грузы
    add_or_update_cargo(
        grz="A123BC",
        status="В пути",
        route="Москва - Санкт-Петербург",
        latitude=55.7558,
        longitude=37.6173
    )

    add_or_update_cargo(
        grz="B456DE",
        status="Задержан",
        route="Новосибирск - Красноярск",
        latitude=55.0083,
        longitude=82.9357
    )

except sqlite3.IntegrityError as e:
    print(f"Ошибка при работе с базой: {e}")

finally:
    conn.close()

from aiogram import Bot, Dispatcher, F
from aiogram.filters import Command, StateFilter
from aiogram.types import Message, CallbackQuery, InlineKeyboardButton, InlineKeyboardMarkup
from aiogram.fsm.storage.memory import MemoryStorage
from aiogram.fsm.state import State, StatesGroup
from aiogram.fsm.context import FSMContext
import sqlite3
import nest_asyncio
from datetime import datetime
import requests
from aiogram.types.input_file import BufferedInputFile

nest_asyncio.apply()

# Инициализация бота
bot = Bot(token="8032532648:AAEeFai3NCWhQHj0VvvnV8lcvvyoYMWovFo")
storage = MemoryStorage()
dp = Dispatcher(storage=storage)

# Подключение к базе данных
conn = sqlite3.connect('cargo.db', check_same_thread=False)
cursor = conn.cursor()

# Состояния FSM
class FindCargo(StatesGroup):
    choosing_grz = State()

class StatusUpdate(StatesGroup):
    choosing_grz = State()
    choosing_action = State()

# Генерация inline-клавиатуры с GRZ
def get_grz_keyboard():
    cursor.execute("SELECT grz FROM cargos")
    grz_list = [row[0] for row in cursor.fetchall()]

    keyboard = []
    row = []
    for grz in grz_list:
        row.append(InlineKeyboardButton(text=grz, callback_data=f"grz:{grz}"))
        if len(row) == 3:
            keyboard.append(row)
            row = []
    if row:
        keyboard.append(row)
    return InlineKeyboardMarkup(inline_keyboard=keyboard)

# Команда /start
@dp.message(Command("start"))
async def start(message: Message):
    await message.answer(
        "👋 Добро пожаловать!\n"
        "🔍 Поиск груза: /find\n"
        "⚡ Изменить статус: /status"
    )

# Обработчик команды /find
@dp.message(Command("find"))
async def find_cargo_start(message: Message, state: FSMContext):
    await state.clear()
    keyboard = get_grz_keyboard()

    if not keyboard.inline_keyboard:
        await message.answer("Нет доступных грузов")
        return

    await message.answer("Выберите груз для просмотра:", reply_markup=keyboard)
    await state.set_state(FindCargo.choosing_grz)

# Обработчик выбора GRZ для поиска
@dp.callback_query(StateFilter(FindCargo.choosing_grz), F.data.startswith("grz:"))
async def show_cargo_info(callback: CallbackQuery, state: FSMContext):
    await state.clear()
    grz = callback.data.split(":")[1]

    cursor.execute("SELECT * FROM cargos WHERE grz = ?", (grz,))
    cargo = cursor.fetchone()

    if not cargo:
        await callback.message.answer("Груз не найден ❌")
        return

    if cargo[3] and cargo[4]:
        map_url = (
            f"https://static-maps.yandex.ru/1.x/"
            f"?ll={cargo[4]},{cargo[3]}"
            f"&size=600,300"
            f"&z=10"
            f"&l=map"
            f"&pt={cargo[4]},{cargo[3]},pm2rdm"
        )

        try:
            response = requests.get(map_url, timeout=10)
            response.raise_for_status()
            photo = BufferedInputFile(response.content, filename=f"map_{grz}.png")

            await callback.message.answer_photo(
                photo=photo,
                caption=(
                    f"🚚 Груз {cargo[0]}\n"
                    f"📊 Статус: {cargo[1]}\n"
                    f"🗺 Маршрут: {cargo[2]}\n"
                    f"🕒 Обновлено: {cargo[5]}"
                )
            )
        except requests.exceptions.RequestException:
            await callback.message.answer(
                f"груз {cargo[0]}\n"
                f"Статус: {cargo[1]}\n"
                f"Маршрут: {cargo[2]}\n"
                "⚠️ Не удалось загрузить карту"
            )
    else:
        await callback.message.answer(
            f"груз {cargo[0]}\n"
            f"Статус: {cargo[1]}\n"
            f"Маршрут: {cargo[2]}\n"
            "⚠️ Координаты не доступны"
        )

# Команда /status
@dp.message(Command("status"))
async def change_status_start(message: Message, state: FSMContext):
    await state.clear()
    keyboard = get_grz_keyboard()

    if not keyboard.inline_keyboard:
        await message.answer("Нет доступных грузов")
        return

    await message.answer("Выберите груз для изменения статуса:", reply_markup=keyboard)
    await state.set_state(StatusUpdate.choosing_grz)

# Обработчик выбора GRZ для изменения статуса
@dp.callback_query(StateFilter(StatusUpdate.choosing_grz), F.data.startswith("grz:"))
async def choose_status_action(callback: CallbackQuery, state: FSMContext):
    grz = callback.data.split(":")[1]
    await state.update_data(selected_grz=grz)

    markup = InlineKeyboardMarkup(inline_keyboard=[
        [InlineKeyboardButton(text="Активировать ЭНП", callback_data="status:activate")],
        [InlineKeyboardButton(text="Деактивировать ЭНП", callback_data="status:deactivate")]
    ])

    await callback.message.answer(f"Выбран груз: {grz}\nВыберите действие:", reply_markup=markup)
    await state.set_state(StatusUpdate.choosing_action)

# Обработчик выбора действия для статуса
@dp.callback_query(StateFilter(StatusUpdate.choosing_action), F.data.startswith("status:"))
async def update_status(callback: CallbackQuery, state: FSMContext):
    action = callback.data.split(":")[1]
    new_status = "Активирована ✅" if action == "activate" else "Деактивирована ❌"

    data = await state.get_data()
    grz = data.get("selected_grz")

    if not grz:
        await callback.message.answer("Ошибка выбора груза")
        return

    cursor.execute('''
        UPDATE cargos
        SET status = ?, last_update = ?
        WHERE grz = ?
    ''', (new_status, datetime.now(), grz))

    cursor.execute('''
        INSERT INTO status_history (grz, status, timestamp)
        VALUES (?, ?, ?)
    ''', (grz, new_status, datetime.now()))

    conn.commit()

    await callback.message.answer(f"Статус груза {grz} изменен: {new_status}")
    await state.clear()

async def main():
    await dp.start_polling(bot)

if __name__ == '__main__':
    import asyncio
    asyncio.run(main())